### PR TITLE
Introduce 1.19.0 support

### PR DESCRIPTION
**Pull request by DissiNL**
Versions:
 - Minecraft version 1.19.0 now has an official 1.0.0 release of this mod.

Automated releases:
- Add the ability to automatically publish releases to releases page
- file for controlling github releases: .github/workflows/publish-release.yml  
- Examples available: https://github.com/DissiNL/FabricQuarry/releases
- Release names based on the version of the mod.

Mod:
 - Ability to build for 1.19.0
 - Switch to java 17
 - Reformat to default IntelliJ settings
 - Calculation about the minable area is done once per depth. Reset area on mining tube changes.
 - Abbreviations renamed to full names.

### CODE REVIEW

**Comment by TED-inc** [comment]
Looks good to me. Small request - my original idea of repository structure was - master is first last actively supported version. And also, different branches for different versions. So, please, create 1.19 branch, merge it there. If u r not planning to support 1.16, 1.17 and 1.18 - u can then merge 1.19 to master

**Comment by DissiNL** [comment]
Good idea. I'll make sure the master branch is 1.19.
For now, I will create a 1.19 branch and make a PR to this.

If I got it correctly, would it mean that I:

1. will make a PR from my repo to 1.19 branch (this one now)
2. Make a PR from 1.19 branch to master after it's been merged

**Comment by TED-inc** [comment]
Exactly. U can merge this PR by ur own

**Comment by TED-inc** [comment]
And also, please update 1.18 branch, and post 1.18.2 and 1.19 builds in CurseForge

**Comment by DissiNL** [comment]
Will do, I was unsure if it was what you envisioned 😄 . Now I know what structure you meant. Will update everything accordingly.

**Pull request merged**
